### ISSUE TITLE
Fails to build on Flutter 3.29.0

### ISSUE THREAD

**Issue by woelmer** [caseyryan/flutter_notification_channel#9]
I created a new flutter application with the latest Flutter 3.29.0 with `flutter create --platforms=android,ios new_flutter_app`

I added the dependency to this plugin in the pubspec.yaml flutter_notification_channel: 3.1.0

I am getting the following error on Android

flutter_notification_channel-3.1.0/android/src/main/java/com/softmaestri/notification/channel/flutter_notification_channel/FlutterNotificationChannelPlugin.java:21: error: cannot find symbol
import io.flutter.plugin.common.PluginRegistry.Registrar;
                                              ^
  symbol:   class Registrar
  location: interface PluginRegistry
1 error```

**Comment by woelmer** [comment]
Looks like the Registrar has been deprecated. https://benamorn.medium.com/today-i-learned-after-upgrading-to-flutter-3-29-0-7c7ab1a97975

**Comment by woelmer** [comment]
https://docs.flutter.dev/release/breaking-changes/plugin-api-migration

**Comment by mrnusa** [comment]
fix it please

**Comment by caseyryan** [comment]
Sorry, I don't have time for it at all. If anyone wants to fix it and make a pull request, I'll gladly merge and and publish the new version

**Comment by szabot0412** [comment]
Hi.
I made a pull request with the fix.
Only an unused import caused the problem.

**Comment by baxruzismailov** [comment]
flutter_notification_channel:
    git:
      url: https://github.com/baxruzismailov/my_flutter_notification_channel_custom.git


![Image](https://github.com/user-attachments/assets/3bfb223f-c4ff-4dd4-a605-b1de0a2a77b8)

bug fixed

**Comment by NaMeTaKeN33** [comment]
@caseyryan -- Can you approve the PR

**Comment by caseyryan** [comment]
Hi guys, sorry for the late reply
Pushed to 3.1.1 https://pub.dev/packages/flutter_notification_channel
@szabot0412 thanks for your help!
